sudo: required
services:
  - docker

before_install:
  - docker build -t piotrfer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true piotrfer/react-test npm test -- --coverage

after_success:
  - docker build -t piotrferensztajn/docker-multi-container:multi-client ./client
  - docker build -t piotrferensztajn/docker-multi-container:multi-nginx ./nginx
  - docker build -t piotrferensztajn/docker-multi-container:multi-server ./server
  - docker build -t piotrferensztajn/docker-multi-container:multi-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push piotrferensztajn/docker-multi-container:multi-client
  - docker push piotrferensztajn/docker-multi-container:multi-nginx
  - docker push piotrferensztajn/docker-multi-container:multi-server
  - docker push piotrferensztajn/docker-multi-container:multi-worker
